### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by jose3898** [yachielab/SPADE#9]
I am sorry, I am a beginner in dev, and I don't know what to do about this problem I had:

root@DESKTOP-L7AOGJP:/mnt/c/Users/jose3/SPADE-master# python3 SPADE.py -in GCF_000014485.1_ASM1448v1_genomic.gbff
Traceback (most recent call last):
  File "SPADE.py", line 1198, in <module>
    import visualisation as vs
  File "/mnt/c/Users/jose3/SPADE-master/visualisation.py", line 14, in <module>
    import genbank_viewer as gv
  File "/mnt/c/Users/jose3/SPADE-master/genbank_viewer.py", line 4, in <module>
    from Bio import Alphabet
  File "/usr/local/lib/python3.8/dist-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

If you could help me, I would be extremely thankful.

**Comment by asd1864714** [comment]
Your python and biopython versions are too high, some packages have been deleted, try to install python3.6.1 and biopython1.76
